name: Lambda Deployment

on:
  push:
    branches: [master]

jobs:
  deploy-to-lambda:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python (AWS CLI dependency)
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install AWS CLI
        run: pip install awscli

      - name: Package Lambda function
        run: zip -r function.zip index.js

      - name: Deploy to AWS Lambda
        run: |
          aws configure set region ${{ secrets.AWS_REGION }}
          aws lambda update-function-code --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} --zip-file fileb://function.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
